// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package mock_main is a generated GoMock package.
package mock_main

import (
	reflect "reflect"

	main "github.com/Smart-Word-Card/web-apis"
	fiber "github.com/gofiber/fiber/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockIManageRoutes is a mock of IManageRoutes interface.
type MockIManageRoutes struct {
	ctrl     *gomock.Controller
	recorder *MockIManageRoutesMockRecorder
}

// MockIManageRoutesMockRecorder is the mock recorder for MockIManageRoutes.
type MockIManageRoutesMockRecorder struct {
	mock *MockIManageRoutes
}

// NewMockIManageRoutes creates a new mock instance.
func NewMockIManageRoutes(ctrl *gomock.Controller) *MockIManageRoutes {
	mock := &MockIManageRoutes{ctrl: ctrl}
	mock.recorder = &MockIManageRoutesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIManageRoutes) EXPECT() *MockIManageRoutesMockRecorder {
	return m.recorder
}

// CreateCollection mocks base method.
func (m *MockIManageRoutes) CreateCollection(ctx *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockIManageRoutesMockRecorder) CreateCollection(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockIManageRoutes)(nil).CreateCollection), ctx)
}

// GetCollection mocks base method.
func (m *MockIManageRoutes) GetCollection(ctx *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockIManageRoutesMockRecorder) GetCollection(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockIManageRoutes)(nil).GetCollection), ctx)
}

// ProvideRoutes mocks base method.
func (m *MockIManageRoutes) ProvideRoutes(fiberApp *main.FiberApp) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProvideRoutes", fiberApp)
}

// ProvideRoutes indicates an expected call of ProvideRoutes.
func (mr *MockIManageRoutesMockRecorder) ProvideRoutes(fiberApp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideRoutes", reflect.TypeOf((*MockIManageRoutes)(nil).ProvideRoutes), fiberApp)
}
